### ISSUE TITLE
config file not working

### ISSUE THREAD

**Issue by nielsalkema** [bmildren/proxysql_ansible_modules#3]
I don't see any documentation on how the config_file should be defined ?

It fails when I create a file /home/foo/proxysql.cnf with

```
login_user: 'radmin'
login_password: 'radmin'
```
or like this 

```
"login_user": "radmin"
"login_password": "radmin"
```
In my main.yml file I have

```
- proxysql_mysql_users:
    config_file: '~/foo.cnf'
    username: 'test'
    state: absent
```
Any idea what I do wrong ?
